
DROP TABLE IF EXISTS "page";
DROP TABLE IF EXISTS schedule;
DROP TABLE IF EXISTS presenter;
DROP TABLE IF EXISTS news;
DROP TABLE IF EXISTS gallery;
DROP TABLE IF EXISTS contact;
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS music;
DROP TABLE IF EXISTS upload;
DROP TABLE IF EXISTS event;
